attic/about/urls.py
"""Натройка URL приложения about"""
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('site/', views.AboutSiteView.as_view(), name='site'),
]

attic/attic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls', namespace='books')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

attic/books/urls.py
"""Натройка URL приложения books"""
from django.urls import path

from books import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('subgenre/<int:id_genre>/', views.subgenre, name='subgenre'),
    path('books-list/<int:id_subgenre>/', views.books_list, name='books_list'),
    path('new-books-list/', views.new_books_list, name='new_books_list'),
    path('book/<int:id_book>/', views.book, name='book'),
    path('create-book/', views.create_book, name='create_book'),
    path('update-book/<int:id_book>', views.update_book, name='update_book'),
    path(
        'book/<int:id_book>/comment/',
        views.create_comment,
        name='create_comment'
    ),
    path(
        'book/<int:id_book>/comment/<int:id_comment>',
        views.delete_comment,
        name='delete_comment'
    ),
    path('authors/', views.authors, name='authors'),
    path(
        'author-books-list/<str:author>',
        views.author_books_list,
        name='author_books_list'
    ),
]

attic/templates/includes/footer.html
<p>© {% now "Y" %} Copyright <span>Аттик</p>

attic/templates/includes/header.html
{% load static %}

{% with request.resolver_match.view_name as view_name %} 
<style>
  .nav-link.active {
    background-color: white !important;
  }
</style>

<nav class="navbar navbar-light" style="background-color: #87FACE">
  <div class="container">
    <div class="d-flex align-items-center">
      <a class="navbar-brand mr-auto" href="{% url 'books:index' %}">
        <img
          src="{% static 'img/logo.png' %}"
          width="90" height="90"
          class="d-inline-block align-top"
          alt=""
        >
      </a>
      <a class="navbar-brand mr-auto" href="{% url 'books:index' %}">
      <span class="h1 ml-2 my-0">Аттик</span>
      </a>
    </div>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link link-dark
          {% if view_name == 'books:create_book' %}
            active
          {% endif %} active-white" href="{% url 'books:create_book' %}"><h5>Добавить книгу</h5>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-dark 
          {% if view_name == 'books:index' %}
            active
          {% endif %} active-white" href="{% url 'books:index' %}"><h5>Каталог книг</h5>
        </a>
      </li>
        <li class="nav-item">
          <a class="nav-link link-dark
            {% if view_name == 'books:authors' %}
              active
            {% endif %} active-white" href="{% url 'books:authors' %}"><h5>Авторы</h5>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark
            {% if view_name == 'books:new_books_list' %}
              active
            {% endif %} active-white" href="{% url 'books:new_books_list' %}"><h5>Новые книги на сайте</h5>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark
            {% if view_name == 'about:site' %}
              active
            {% endif %} active-white" href="{% url 'about:site' %}"><h5>О сайте</h5>
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          Пользователь: {{ user.username }}
          <a class="nav-link link-dark
             {% if view_name  == 'users:password_change' %}
               active
             {% endif %}"
             href="{% url 'users:password_change' %}">Изменить пароль
          </a>

          <a class="nav-link link-dark
             {% if view_name  == 'users:logout' %}
               active
             {% endif %}"
             href="{% url 'users:logout' %}">Выйти
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-dark
             {% if view_name  == 'users:login' %}
               active
             {% endif %}"
             href="{% url 'users:login' %}">Войти
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark
             {% if view_name  == 'users:signup' %}
               active
             {% endif %}"
             href="{% url 'users:signup' %}">Регистрация
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>      
{% endwith %}