attic/about/urls.py
"""Натройка URL приложения about"""
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('site/', views.AboutSiteView.as_view(), name='site'),
]

attic/attic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls', namespace='books')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

attic/users/urls.py
"""Натройка URL приложения users"""
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='reset_ui_token'
    ),
]

attic/users/forms.py
"""Формы для приложения users."""
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    """Форма регистрации пользователя."""
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

attic/users/views.py
"""Обработчики URL запросов."""
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    """Переадресация пользователя после авторизации."""
    form_class = CreationForm
    success_url = reverse_lazy('books:index')
    template_name = 'users/signup.html'


def authorized_only(func):
    """Проверка авторизации пользователя."""
    def check_user(request, *args, **kwargs):
        if request.user.is_authenticated:
            return func(request, *args, **kwargs)
        return redirect('/auth/login/')
    return check_user

attic/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
  {% with card_header='Выход' card_body='Вы вышли из своей учётной записи. Ждём вас снова!' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

attic/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти{% endblock %}

{% block content %}

{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Войти на сайт
      </div>
      <div class="card-body">
        {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger"
                {{ error|escape }}
              </div>
            {% endfor %}
        {% endif %}

        <form method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >

        {% csrf_token %}

        {% for field in form %}
          <div class="form-group row my-3"
            {% if field.field.required %} 
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}
          >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            <div>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small 
                  id="{{ field.id_for_label }}-help"
                  class="form-text text-muted"
                >
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
        {% endfor %}
        <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">
            Войти
          </button>
          <a href="{% url 'users:password_reset' %}" class="btn btn-link">
            Забыли пароль?
          </a>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

attic/templates/users/password_change_done.html
{% extends "base.html" %}

{% block title %}Пароль изменён{% endblock %}

{% block content %}
  {% with card_header='Пароль изменён' card_body='Пароль изменён успешно' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

attic/templates/users/password_change_form.html
{% extends "base.html" %}

{% block title %}Изменить пароль{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Изменить пароль</div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_change' %}">
          {% csrf_token %}
          {% include 'users/includes/form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

attic/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
  {% with card_header='Восстановление пароля завершено' card_body='Ваш пароль был сохранен. Используйте его для входа' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

attic/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Новый пароль{% endblock %}

{% block content %}

{% load user_filters %}

{% if validlink %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post">
          {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль        
                <span class="required text-danger">*</span>        
              </label>    
              <input 
                type="password" 
                name="new_password1" 
                class="form-control" 
                required id="id_new_password1"
              >      
              <small id="id_new_password1-help" class="form-text text-muted">
                <ul>
                  <li>
                    Ваш пароль не должен совпадать с вашим именем или 
                    другой персональной информацией или быть слишком похожим на неё.
                  </li>
                  <li>
                    Ваш пароль должен содержать как минимум 8 символов.
                  </li>
                  <li>
                    Ваш пароль не может быть одним из широко распространённых паролей.
                  </li>
                  <li>
                    Ваш пароль не может состоять только из цифр.
                  </li>
                </ul>
              </small>      
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля        
                <span class="required text-danger">*</span>        
              </label>    
              <input 
                type="password" 
                name="new_password2" 
                class="form-control" 
                required id="id_new_password2"
              >      
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Ошибка
        </div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

attic/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}Сбросить пароль{% endblock %}

{% block content %}
  {% with card_header='Отправлено письмо' card_body='Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

attic/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block title %}Сбросить пароль{% endblock %}

{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — 
          введите адрес электронной почты, 
          под которым вы регистрировались
        </div>
        <div class="card-body"> 
          <form method="post" action="{% url 'users:password_reset' %}">
          {% csrf_token %}
          {% include 'users/includes/form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock %}

attic/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Зарегистрироваться{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% include 'users/includes/form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}