attic/about/urls.py
"""Натройка URL приложения about"""
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('site/', views.AboutSiteView.as_view(), name='site'),
]

attic/attic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls', namespace='books')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

attic/books/urls.py
"""Натройка URL приложения books"""
from django.urls import path

from books import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('subgenre/<int:id_genre>/', views.subgenre, name='subgenre'),
    path('books-list/<int:id_subgenre>/', views.books_list, name='books_list'),
    path('new-books-list/', views.new_books_list, name='new_books_list'),
    path('book/<int:id_book>/', views.book, name='book'),
    path('create-book/', views.create_book, name='create_book'),
    path('update-book/<int:id_book>', views.update_book, name='update_book'),
    path(
        'book/<int:id_book>/comment/',
        views.create_comment,
        name='create_comment'
    ),
    path(
        'book/<int:id_book>/comment/<int:id_comment>',
        views.delete_comment,
        name='delete_comment'
    ),
    path('authors/', views.authors, name='authors'),
    path(
        'author-books-list/<str:author>',
        views.author_books_list,
        name='author_books_list'
    ),
]

attic/books/models.py
"""Натройка моделей приложения books."""
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

User = get_user_model()


class Genre(models.Model):
    """Модель Genre для Attic."""

    class Meta:
        """Дефолтная сортировка модели Genre."""
        ordering = ['name']
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    name = models.TextField(
        verbose_name='Жанр книги',
        help_text='Жанр книги',
    )

    def __str__(self):
        """Вывод поля genre."""
        return self.name


class SubGenre(models.Model):
    """Модель SubGenre для Attic."""

    class Meta:
        """Дефолтная сортировка модели SubGenre."""
        ordering = ['name']
        verbose_name = 'Поджанр'
        verbose_name_plural = 'Поджанры'

    name = models.TextField(
        verbose_name='Поджанр книги',
        help_text='Поджанр книги',
    )
    genre = models.ForeignKey(
        Genre,
        on_delete=models.CASCADE,
        related_name='subgenres',
        verbose_name='Жанр',
    )

    def __str__(self):
        """Вывод поля subgenre."""
        return self.name


class Book(models.Model):
    """Модель Book для Attic."""

    class Meta:
        """Дефолтная сортировка модели Book."""
        ordering = ['-book_add_date']
        verbose_name = 'Книги'
        verbose_name_plural = 'Книги'

    subgenre = models.ForeignKey(
        SubGenre,
        on_delete=models.CASCADE,
        related_name='books',
        verbose_name='Поджанр',
    )
    name = models.TextField(
        verbose_name='Название книги',
        help_text='Название книги',
    )
    text = models.TextField(
        verbose_name='Описание книги',
        help_text='Описание книги',
    )
    author = models.TextField(
        verbose_name='Автор книги',
        help_text='Автор книги',
    )
    pub_house = models.TextField(
        verbose_name='Издательство',
        help_text='Издательство',
    )
    pub_year = models.PositiveIntegerField(
        verbose_name='Год издания',
        help_text='Год издания',
        validators=[
            MinValueValidator(1000),
            MaxValueValidator(3000),
        ],
    )
    image = models.ImageField(
        upload_to='books/',
        blank=True,
        verbose_name='Картинка',
    )
    book_add_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата добавления книги',
    )

    def __str__(self):
        """Вывод поля name."""
        return self.name


class Comment(models.Model):
    """Модель Comment для Attic."""

    class Meta:
        """Дефолтная сортировка модели Comment."""
        ordering = ['-created']

    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Вывод поля text."""
        return self.text

attic/books/forms.py
from django import forms

from books.models import Book, Comment


class BookForm(forms.ModelForm):
    """Форма создания/редактирования книг."""

    class Meta:
        model = Book
        fields = (
            'subgenre', 'name', 'text',
            'author', 'pub_house', 'pub_year',
            'image',
        )


class CommentForm(forms.ModelForm):
    """Форма создания/редактирования комментариев."""
    text = forms.CharField()

    class Meta:
        model = Comment
        fields = (
            'text',
        )

attic/books/views.py
"""Обработчики URL запросов."""
from django.shortcuts import (get_list_or_404, get_object_or_404, redirect,
                              render)
from django.urls import reverse

from books.forms import BookForm, CommentForm
from books.models import Book, Genre, SubGenre, Comment
from users.views import authorized_only


def index(request):
    """Главная страница."""
    genres = get_list_or_404(Genre)
    return render(
        request,
        'books/index.html',
        {
            'genres': genres
        }
    )


def subgenre(request, id_genre):
    """Страница с поджанрами."""
    subgenres = get_list_or_404(SubGenre, genre=id_genre)
    return render(
        request,
        'books/subgenre.html',
        {
            'subgenres': subgenres
        }
    )


def books_list(request, id_subgenre):
    """Страница со списком книг."""
    books = get_list_or_404(Book, subgenre=id_subgenre)
    return render(
        request,
        'books/books_list.html',
        {
            'books': books
        }
    )


def author_books_list(request, author):
    author_books = get_list_or_404(Book, author=author)
    return render(
        request,
        'books/books_list.html',
        {
            'books': author_books
        }
    )


def new_books_list(request):
    books = get_list_or_404(Book)[:10]
    return render(
        request,
        'books/books_list.html',
        {
            'books': books
        }
    )


def book(request, id_book):
    book = get_object_or_404(Book, id=id_book)
    comments = Comment.objects.filter(book=id_book)
    form = CommentForm()
    return render(
        request,
        'books/book.html',
        {
            'book': book,
            'comments': comments,
            'form': form
        }
    )


@authorized_only
def create_book(request):
    form = BookForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect(reverse('books:new_books_list'))
    return render(request, 'books/create_book.html', {'form': form})


@authorized_only
def update_book(request, id_book):
    book = get_object_or_404(Book, id=id_book)
    form = BookForm(
        request.POST or None,
        files=request.FILES or None,
        instance=book
    )

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('books:book', id_book=id_book)
    return render(
        request,
        'books/create_book.html',
        {
            'form': form,
            'is_edit': True,
        }
    )


@authorized_only
def create_comment(request, id_book):
    book = get_object_or_404(Book, id=id_book)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.book = book
        comment.save()
    return redirect('books:book', id_book=id_book)


@authorized_only
def delete_comment(request, id_comment, id_book):
    comment = get_object_or_404(Comment, id=id_comment)
    comment.delete()
    return redirect('books:book', id_book=id_book)


def authors(request):
    authors = sorted(list(set(Book.objects.values_list('author', flat=True))))
    return render(
        request,
        'books/authors.html',
        {
            'authors': authors
        }
    )

attic/templates/books/authors.html
{% extends 'base.html' %}

{% block title %}
Авторы
{% endblock %}

{% block content %}
<div>
    <h1>
        Авторы
    </h1>
</div>
<div style="column-count: 3; column-gap: 20px; margin-bottom: 20px;">
    {% for author in authors %}
        <li>
            <a href="{% url 'books:author_books_list' author %}">
                {{ author }}
            </a>
        </li>
    {% endfor %}
</div>
{% endblock %}

attic/templates/books/book.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
Книги
{% endblock %}

{% block content %}
<style>
    .book-details {
        display: flex;
        align-items: center;
        margin-bottom: 50px;
    }

    .book-info {
        margin-left: 20px;
    }

    .book-description {
        margin-top: 20px;
    }

    .book-image {
        width: 300px;
        height: 300px;
        object-fit: contain;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .book-title {
        font-size: 24px;
        margin-top: 0;
    }

    .book-info p {
        margin-top: 10px;
    }

    .book-info strong {
        font-weight: bold;
    }

    .book-description p {
        margin: 0;
        overflow-wrap: break-word;
    }
    
    .book-details-container {
        display: flex;
        flex-direction: row;
    }

    .book-image-container {
        flex: 1;
    }

    .book-text-container {
        flex: 4;
        margin-left: 30px;
    }

    .book-description-container {
        flex: 2;
        margin-left: 50px;
        max-width: 400px;
    }
</style>

<div class="book-details">
    <div class="book-details-container">
        <div class="book-image-container">
            {% thumbnail book.image "2000x2000" crop="center" upscale=False as im %}
                <img class="book-image" src="{{ im.url }}" alt="{{ book.name }}">
            {% endthumbnail %}
        </div>
        <div class="book-text-container">
            <h5 class="book-title">{{ book.name }}</h5>
            <div class="book-info">
                <p><strong>Автор:</strong> {{ book.author }}</p>
                <p><strong>Жанр:</strong> {{ book.subgenre.genre.name }}</p>
                <p><strong>Поджанр:</strong> {{ book.subgenre.name }}</p>
                <p><strong>Год издания:</strong> {{ book.pub_year }}</p>
                <p><strong>Издательство:</strong> {{ book.pub_house }}</p>
                <p><strong>ID книги:</strong> {{ book.id }}</p>
            </div>
        </div>
        <div class="book-description-container">
            <div class="book-info">
                <p><strong>Описание книги:</strong></p>
                <p style="max-width: 100%;">{{ book.text }}</p>
                <a class="btn btn-primary" href="{% url 'books:update_book' book.id %}">
                    Редактировать
                </a>
            </div>
        </div>
    </div>
</div>
{% include 'books/includes/comment.html' %}
{% endblock %}

attic/templates/books/books_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
Книги
{% endblock %}

{% block content %}
    <style>
        .grid-container {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            grid-gap: 20px;
            margin-bottom: 20px;
        }
        .grid-item {
            width: 200px;
            height: 400px;
        }
        .card {
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }
        .no-image-placeholder {
            width: 100%;
            height: 100%;
            background-color: #eee;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
            overflow: hidden;
        }
        .no-image-placeholder span {
            color: #888;
            font-size: 16px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
        .card-img-top {
            width: 100%;
            height: 250px;
            object-fit: cover;
            padding: 10px;
        }
        .card-body {
            padding-bottom: 0;
        }
        .card-footer {
            padding-top: 10px;
            text-align: center;
            background-color: #f5f5f5;
        }
    </style>

    <div class="content">
        <div class="grid-container">
            {% for book in books %}
            <div class="grid-item">
                
                <div class="card mb-4">
                    {% if book.image %}
                        {% thumbnail book.image "2000x2000" crop="center" upscale=False as im %}
                        <a href="{% url 'books:book' book.id %}">
                            <img class="card-img-top" src="{{ im.url }}" alt="{{ book.name }}">
                        </a>
                        {% endthumbnail %}
                    {% else %}
                        <div class="no-image-placeholder">
                            <span>No Image</span>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <a href="{% url 'books:book' book.id %}">
                            <h5 class="card-title">{{ book.name }}</h5>
                        </a>
                        <p class="card-text">Автор: {{ book.author }}</p>
                    </div>
                    <div class="card-footer">
                        <p class="card-text">ID книги: {{ book.id }}</p>
                    </div>
                </div>
                
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

attic/templates/books/create_book.html
{% extends 'base.html' %}

{% block title %}
{% if is_edit %}
  Редактирование
{% else %}
  Новая книга
{% endif %} 
{% endblock %}

{% block content %} 
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Новая книга
      </div>
      <div class="card-body">
        {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >

        {% csrf_token %}

        {% for field in form %}
          <div class="form-group row my-3 p-3"
            {% if field.field.required %}
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}
          >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            
            <div>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">
            {% if is_edit %}
              Сохранить
            {% else %}
              Добавить
            {% endif %}
          </button>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

attic/templates/books/index.html
{% extends 'base.html' %}

{% block title %}
Каталог книг
{% endblock %}

{% block content %}
<div>
    <h1>
        Каталог книг
    </h1>
</div>
<div style="column-count: 3; column-gap: 20px; margin-bottom: 20px;">
    {% for genre in genres %}
    <div>
        <ul>
            <li>
                <a href="{% url 'books:subgenre' genre.id %}">
                    <h4>
                        {{ genre }}
                    </h4>
                </a>
            </li>
        </ul>
    </div>
    {% endfor %}
</div>
{% endblock %}

attic/templates/books/sub_genre.html
{% extends 'base.html' %}

{% block title %}
Жанры
{% endblock %}

{% block content %}
<div>
    <h1>
        Поджанры
    </h1>
</div>
<div style="column-count: 3; column-gap: 20px; margin-bottom: 20px;">
    {% for sub_genre in sub_genres %}
    <div>
        <ul>
            <li>
                <a href="{% url 'books:books_list' sub_genre.id %}">
                    <h4>
                        {{ sub_genre }}
                    </h4>
                </a>
            </li>
        </ul>
    </div>
    {% endfor %}
</div>
{% endblock %}

attic/templates/books/subgenre.html
{% extends 'base.html' %}

{% block title %}
Жанры
{% endblock %}

{% block content %}
<div>
    <h1>
        Поджанры
    </h1>
</div>
<div style="column-count: 3; column-gap: 20px; margin-bottom: 20px;">
    {% for subgenre in subgenres %}
    <div>
        <ul>
            <li>
                <a href="{% url 'books:books_list' subgenre.id %}">
                    <h4>
                        {{ subgenre }}
                    </h4>
                </a>
            </li>
        </ul>
    </div>
    {% endfor %}
</div>
{% endblock %}